### ISSUE TITLE
Need a nice JSON schema browser / viewer

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/billing-semantics#10]
Once we have nice tight JSON schema as per #9, then we need to be able to display them for human browning - so that developers can understand the structure.   Lets research a few tools that can provide that view and pick the best one.

**Comment by monkeypants** [comment]
https://github.com/mattyod/matic
https://github.com/salesking/json-schema-browser
https://github.com/cloudflare/json-schema-docs-generator
https://github.com/lbovet/docson

?

**Comment by kshychko** [comment]
docson has been integrated to ausdigital.io
any json file can be rendered with the following link:
http://ausdigital.org/docson.html#%path_to_file%
for example:
http://ausdigital.org/docson.html#https://raw.githubusercontent.com/ausdigital/billing-semantics/master/spec/v1.0.0/Invoice.json

**Comment by onthebreeze** [comment]
Done - nice.  Added links to the billing semantics specificatio at http://billing-semantics.readthedocs.io/en/latest/Billing-Documents/

**Comment by monkeypants** [comment]
Should we try to "top and tail" the schema browser with an ausdigital masthead/footer/menu, to provide context? If we do that, should we also add a tweak to ensure it only renders schemata from a whitelist?
