### ISSUE TITLE
ADBC XSD Schema library is broken - missing XSD files.

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/billing-semantics#2]
The Digital business council published schema files for billing semantics to the [Software and service providers](http://digitalbusinesscouncil.com.au/software-and-service-providers) page (right hand panel, documents 3, 4 and "DBC-AU" artefacts).

All the artefacts have been copied to this [github repository path](https://github.com/ausdigital/billing-semantics/tree/master/DBC_docs)

Unfortunately the runtime XSD files in the [xsrdt](https://github.com/ausdigital/billing-semantics/tree/master/DBC_docs/DBC-AU/xsdrt) folder do not validate.  neither do the main UBL files in the /xsd folder.  This is largely due to missing imported schema files. For example
* CoreInvoice-1.0.xsd  exists and imports
* UBL-CommonAggregateComponents-2.1.xsd which exists and imports
* UBL-CommonBasicComponents-2.1.xsd which exists and imports
* UBL-UnqualifiedDataTypes-2.1.xsd which does NOT exist but can be found via web search.  It imports 
* CCTS_CCT_SchemaModule-2.1.xsd  - which also does NOT exist

Also:
* CoreInvoice-1.0.xsd exists and also imports:
* UBL-CommonExtensionComponents-2.1.xsd - which does NOT exist either.  But it imports
* UBL-ExtensionContentDataType-2.1.xsd - which is also missing.  So tracked that down.   But it imports 
* UBL-CommonSignatureComponents-2.1.xsd - which was missing.  So I tracked it down and added it.  But it imports
* UBL-SignatureAggregateComponents-2.1.xsd - which was missing.  So I tracked that down and added.   But it imports
* BL-SignatureBasicComponents-2.1.xsd and UBL-xmldsig-core-schema-2.1.xsd and UBL-XAdESv132-2.1.xsd and UBL-XAdESv141-2.1.xsd - ALL of which are missing.

Most (hopefully all) of the missing files can be sourced from internet searches.  

Lets try to first get this rather nasty and complex hierarchy of schema files to work so that the root schema CoreInvoice-1.0.xsd will open and validate in an XSD aware tool.  Add the right files to this github repo until it works.

**Comment by kshychko** [comment]
missing XSD files have been added

**Comment by onthebreeze** [comment]
And now https://github.com/ausdigital/billing-semantics/blob/master/DBC_docs/DBC-AU/xsdrt/maindoc/CoreInvoice-1.0.xsd validates OK.  Good.

**Comment by onthebreeze** [comment]
opening so I can move it to adbc repo

**Comment by onthebreeze** [comment]
This issue was moved to ausdigital/adbc#2
